namespace CDC_PoC.CustomerData;

public class AccountBase
{
    public Guid AccountId { get; set; }
    public int AccountCategoryCode { get; set; }
    public Guid TerritoryId { get; set; }
    public Guid DefaultPriceLevelId { get; set; }
    public int CustomerSizeCode { get; set; }
    public int PreferredContactMethodCode { get; set; }
    public int CustomerTypeCode { get; set; }
    public int AccountRatingCode { get; set; }
    public int IndustryCode { get; set; }
    public int TerritoryCode { get; set; }
    public int AccountClassificationCode { get; set; }
    public int BusinessTypeCode { get; set; }
    public Guid OwningBusinessUnit { get; set; }
    public Guid OriginatingLeadId { get; set; }
    public int PaymentTermsCode { get; set; }
    public int ShippingMethodCode { get; set; }
    public Guid PrimaryContactId { get; set; }
    public bool ParticipatesInWorkflow { get; set; }
    public string Name { get; set; }
    public string AccountNumber { get; set; }
    public decimal Revenue { get; set; }
    public int NumberOfEmployees { get; set; }
    public string Description { get; set; }
    public string SIC { get; set; }
    public int OwnershipCode { get; set; }
    public decimal MarketCap { get; set; }
    public decimal SharesOutstanding { get; set; }
    public string TickerSymbol { get; set; }
    public string StockExchange { get; set; }
    public string WebSiteURL { get; set; }
    public string FtpSiteURL { get; set; }
    public string EMailAddress1 { get; set; }
    public string EMailAddress2 { get; set; }
    public string EMailAddress3 { get; set; }
    public bool DoNotPhone { get; set; }
    public bool DoNotFax { get; set; }
    public string Telephone1 { get; set; }
    public bool DoNotEMail { get; set; }
    public string Telephone2 { get; set; }
    public string Fax { get; set; }
    public string Telephone3 { get; set; }
    public bool DoNotPostalMail { get; set; }
    public bool DoNotBulkEMail { get; set; }
    public bool DoNotBulkPostalMail { get; set; }
    public decimal CreditLimit { get; set; }
    public bool CreditOnHold { get; set; }
    public bool IsPrivate { get; set; }
    public DateTime CreatedOn { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTime ModifiedOn { get; set; }
    public Guid ModifiedBy { get; set; }
    public string VersionNumber { get; set; }
    public Guid ParentAccountId { get; set; }
    public decimal Aging30 { get; set; }
    public int StateCode { get; set; }
    public decimal Aging60 { get; set; }
    public int StatusCode { get; set; }
    public decimal Aging90 { get; set; }
    public int PreferredAppointmentDayCode { get; set; }
    public Guid PreferredSystemUserId { get; set; }
    public int PreferredAppointmentTimeCode { get; set; }
    public bool Merged { get; set; }
    public bool DoNotSendMM { get; set; }
    public Guid MasterId { get; set; }
    public DateTime LastUsedInCampaign { get; set; }
    public Guid PreferredServiceId { get; set; }
    public Guid PreferredEquipmentId { get; set; }
    public decimal ExchangeRate { get; set; }
    public int UTCConversionTimeZoneCode { get; set; }
    public DateTime OverriddenCreatedOn { get; set; }
    public int TimeZoneRuleVersionNumber { get; set; }
    public int ImportSequenceNumber { get; set; }
    public Guid TransactionCurrencyId { get; set; }
    public decimal CreditLimit_Base { get; set; }
    public decimal Aging30_Base { get; set; }
    public decimal Revenue_Base { get; set; }
    public decimal Aging90_Base { get; set; }
    public decimal MarketCap_Base { get; set; }
    public decimal Aging60_Base { get; set; }
    public string YomiName { get; set; }
    public Guid OwnerId { get; set; }
    public Guid ModifiedOnBehalfBy { get; set; }
    public Guid CreatedOnBehalfBy { get; set; }
    public int OwnerIdType { get; set; }
    public bool ExcludeR365Payment { get; set; }
    public int LastPaymentMethod { get; set; }
}